# Generated by Django 2.1.5 on 2019-05-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20190520_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
    ]
