# Generated by Django 2.2 on 2019-04-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20190429_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
