# Generated by Django 2.2 on 2019-04-29 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Organization'),
        ),
    ]
