# Generated by Django 2.1.5 on 2019-06-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandwiches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='allergen',
            field=models.ManyToManyField(to='sandwiches.Allergen'),
        ),
    ]
