# Generated by Django 2.2 on 2019-04-27 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alergeny',
            fields=[
                ('Ale_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Ale_Nazwa', models.TextField(null=True)),
                ('Ale_Ikona', models.BinaryField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kanapki',
            fields=[
                ('Kan_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Kan_Cena', models.FloatField(null=True)),
                ('Kan_Archiwalny', models.IntegerField(null=True)),
                ('KaS_Ikona', models.BinaryField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skladniki',
            fields=[
                ('Skl_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Skl_Grupa', models.IntegerField()),
                ('Skl_Nazwa', models.TextField(null=True)),
                ('Skl_Archiwalny', models.IntegerField(null=True)),
                ('Skl_Kcal', models.IntegerField(null=True)),
                ('Skl_GramNaPorcje', models.IntegerField(null=True)),
                ('Skl_Cena', models.IntegerField(null=True)),
                ('Skl_Ikona', models.BinaryField(null=True)),
            ],
        ),
    ]
