# Generated by Django 2.2 on 2019-04-27 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulka', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkladnikiAlergeny',
            fields=[
                ('SklA_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('SklA_AleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulka.Alergeny')),
                ('SklA_SklId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulka.Skladniki')),
            ],
        ),
    ]
