# Generated by Django 2.2 on 2019-04-27 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulka', '0002_skladnikialergeny'),
    ]

    operations = [
        migrations.CreateModel(
            name='KanapkiSkladniki',
            fields=[
                ('KaS_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Kas_Ilosc', models.IntegerField(null=True)),
                ('KaS_KanId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulka.Kanapki')),
                ('KaS_SklId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulka.Skladniki')),
            ],
        ),
    ]
