# Generated by Django 2.2 on 2019-05-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulka', '0003_kanapkiskladniki'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alergeny',
            name='Ale_Id',
        ),
        migrations.RemoveField(
            model_name='kanapki',
            name='Kan_Id',
        ),
        migrations.RemoveField(
            model_name='kanapkiskladniki',
            name='KaS_Id',
        ),
        migrations.RemoveField(
            model_name='skladniki',
            name='Skl_Id',
        ),
        migrations.RemoveField(
            model_name='skladnikialergeny',
            name='SklA_Id',
        ),
        migrations.AddField(
            model_name='alergeny',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kanapki',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kanapkiskladniki',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skladniki',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skladnikialergeny',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
