# Generated by Django 2.2 on 2019-05-01 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulka', '0004_auto_20190501_1943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kanapki',
            old_name='KaS_Ikona',
            new_name='Kan_Ikona',
        ),
        migrations.RenameField(
            model_name='kanapkiskladniki',
            old_name='Kas_Ilosc',
            new_name='KaS_Ilosc',
        ),
    ]
