# Generated by Django 2.2 on 2019-05-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulka', '0005_auto_20190501_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanapki',
            name='Kan_Nazwa',
            field=models.TextField(null=True),
        ),
    ]
